# Generated by Django 4.0.4 on 2022-05-14 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfIb', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=2555, null=True)),
                ('Titel', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=2555, null=True)),
                ('Titel', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.TextField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IbAccountPage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('IB_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('client_NO', models.IntegerField()),
                ('typye', models.CharField(blank=True, choices=[('star', 'star'), ('', '')], max_length=50, null=True)),
                ('star1', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star2', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star3', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star4', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star5', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star6', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('IB_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IbAccountPage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('IB_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('client_NO', models.IntegerField()),
                ('typye', models.CharField(blank=True, choices=[('star', 'star'), ('', '')], max_length=50, null=True)),
                ('star1', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star2', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star3', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star4', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star5', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star6', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('IB_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IbAccountPage3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('IB_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('client_NO', models.IntegerField()),
                ('typye', models.CharField(blank=True, choices=[('star', 'star'), ('', '')], max_length=50, null=True)),
                ('star1', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star2', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star3', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star4', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star5', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star6', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('IB_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IbAccountPage4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('IB_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('client_NO', models.IntegerField()),
                ('typye', models.CharField(blank=True, choices=[('star', 'star'), ('', '')], max_length=50, null=True)),
                ('star1', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star2', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star3', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star4', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star5', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star6', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('IB_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IbAccountPage5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('IB_number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('client_NO', models.IntegerField()),
                ('typye', models.CharField(blank=True, choices=[('star', 'star'), ('', '')], max_length=50, null=True)),
                ('star1', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star2', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star3', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star4', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star5', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('star6', models.CharField(blank=True, choices=[('checked', 'checked'), ('', '')], max_length=50, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('IB_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(blank=True, max_length=250, null=True)),
                ('first', models.CharField(blank=True, choices=[('active', 'active'), (' ', ' ')], max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('TheComment', models.TextField(max_length=500)),
            ],
        ),
    ]
